import { useQuery } from "@tanstack/react-query";
import { ArrowRight, ScrollText } from "lucide-react";
import { Link } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { fetchPublishedPrayers } from "@/lib/content-display";
export default function PrayersPage() { const { data = [], isLoading, isError } = useQuery({ queryKey: ["published-prayers"], queryFn: fetchPublishedPrayers, staleTime: 10 * 60 * 1000 }); return <main className="min-h-full px-4 py-6 pb-28 lg:px-8"><div className="mx-auto max-w-5xl space-y-6"><header className="rounded-[32px] border border-primary/15 bg-primary/5 p-6 sm:p-8"><p className="text-sm font-bold text-primary">Kanisa Connect</p><h1 className="mt-2 text-4xl font-bold">Sala</h1><p className="mt-2 text-muted-foreground">Sala zilizochapishwa kwa ukuaji wa maisha ya kiroho.</p></header>{isLoading ? <Skeleton className="h-72 rounded-3xl"/> : isError ? <Card><CardContent className="p-6">Sala hazikuweza kupakiwa. Tafadhali jaribu tena.</CardContent></Card> : data.length === 0 ? <Card><CardContent className="flex flex-col items-center py-14 text-center"><ScrollText className="h-10 w-10 text-muted-foreground"/><p className="mt-4 font-semibold">Hakuna sala iliyochapishwa kwa sasa.</p></CardContent></Card> : <section className="grid gap-4 sm:grid-cols-2">{data.map((prayer) => <Card key={prayer.id} className="rounded-3xl"><CardContent className="p-5">{prayer.featured ? <Badge>Imependekezwa</Badge> : null}<h2 className="mt-3 text-xl font-bold">{prayer.title}</h2><p className="mt-2 line-clamp-4 text-sm leading-6 text-muted-foreground">{prayer.summary || prayer.body}</p><Button asChild variant="outline" className="mt-5 min-h-11 w-full rounded-2xl"><Link to={`/portal/prayers/${prayer.slug}`}>Soma sala<ArrowRight className="ml-2 h-4 w-4"/></Link></Button></CardContent></Card>)}</section>}</div></main>; }
