import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { SupabaseClient } from "@supabase/supabase-js";
import { CalendarDays, Loader2, Plus, RefreshCw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { MASS_WEEKDAYS, formatMassDate, formatMassTime, validateMassTimes, type MassOccurrence, type MassSchedule } from "@/lib/mass-timetable";

const db = supabase as unknown as SupabaseClient;
const tzDate = (days = 0) => new Intl.DateTimeFormat("en-CA", { timeZone: "Africa/Dar_es_Salaam" }).format(new Date(Date.now() + days * 86400000));
type ScheduleForm = { id?: string; name: string; day_of_week: string; start_time: string; end_time: string; location_name: string; language: string; default_celebrant_name: string; intention_capacity: string; default_intention_fee: string; accepts_intentions: boolean; effective_from: string; effective_until: string; is_active: boolean };
const emptyForm = (): ScheduleForm => ({ name: "", day_of_week: "0", start_time: "06:30", end_time: "", location_name: "", language: "Kiswahili", default_celebrant_name: "", intention_capacity: "", default_intention_fee: "", accepts_intentions: true, effective_from: tzDate(), effective_until: "", is_active: true });

export default function MassTimetablePage() {
  const { churchId } = useAuth(); const { toast } = useToast(); const client = useQueryClient();
  const [form, setForm] = useState<ScheduleForm | null>(null);
  const timetable = useQuery({ queryKey: ["wave4a-mass-timetable", churchId], enabled: !!churchId, queryFn: async () => {
    const [schedules, occurrences] = await Promise.all([
      db.from("mass_schedules").select("*").eq("church_id", churchId).order("day_of_week").order("start_time"),
      db.from("mass_occurrences").select("*").eq("church_id", churchId).gte("occurrence_date", tzDate()).lte("occurrence_date", tzDate(90)).order("occurrence_date").order("start_time"),
    ]); if (schedules.error) throw schedules.error; if (occurrences.error) throw occurrences.error;
    return { schedules: schedules.data as MassSchedule[], occurrences: occurrences.data as MassOccurrence[] };
  }});
  const refresh = () => client.invalidateQueries({ queryKey: ["wave4a-mass-timetable", churchId] });
  const generate = useMutation({ mutationFn: async () => { if (!churchId) throw new Error("Church context required"); const result = await db.rpc("generate_mass_occurrences", { p_church_id: churchId, p_start_date: tzDate(), p_end_date: tzDate(90) }); if (result.error) throw result.error; return Number(result.data ?? 0); }, onSuccess: (count) => { refresh(); toast({ title: "Ratiba imetengenezwa", description: `${count} matukio mapya ya Misa.` }); }, onError: (error: Error) => toast({ title: "Imeshindikana", description: error.message, variant: "destructive" }) });
  const save = useMutation({ mutationFn: async (value: ScheduleForm) => { if (!churchId) throw new Error("Church context required"); if (!value.name.trim() || !validateMassTimes(value.start_time, value.end_time)) throw new Error("Jaza jina na muda sahihi."); const payload = { church_id: churchId, name: value.name.trim(), day_of_week: Number(value.day_of_week), start_time: value.start_time, end_time: value.end_time || null, location_name: value.location_name.trim() || null, language: value.language.trim() || null, default_celebrant_name: value.default_celebrant_name.trim() || null, intention_capacity: value.intention_capacity === "" ? null : Number(value.intention_capacity), default_intention_fee: value.default_intention_fee === "" ? null : Number(value.default_intention_fee), accepts_intentions: value.accepts_intentions, effective_from: value.effective_from, effective_until: value.effective_until || null, is_active: value.is_active }; const result = value.id ? await db.from("mass_schedules").update(payload).eq("id", value.id).eq("church_id", churchId) : await db.from("mass_schedules").insert(payload); if (result.error) throw result.error; }, onSuccess: () => { setForm(null); refresh(); toast({ title: "Ratiba imehifadhiwa" }); }, onError: (error: Error) => toast({ title: "Haijahifadhiwa", description: error.message, variant: "destructive" }) });
  const toggle = useMutation({ mutationFn: async (row: MassSchedule) => { const result = await db.from("mass_schedules").update({ is_active: !row.is_active }).eq("id", row.id).eq("church_id", churchId); if (result.error) throw result.error; }, onSuccess: refresh });
  const openEdit = (row: MassSchedule) => setForm({ id: row.id, name: row.name, day_of_week: String(row.day_of_week), start_time: formatMassTime(row.start_time), end_time: row.end_time ? formatMassTime(row.end_time) : "", location_name: row.location_name ?? "", language: row.language ?? "", default_celebrant_name: row.default_celebrant_name ?? "", intention_capacity: row.intention_capacity == null ? "" : String(row.intention_capacity), default_intention_fee: row.default_intention_fee == null ? "" : String(row.default_intention_fee), accepts_intentions: row.accepts_intentions, effective_from: row.effective_from, effective_until: row.effective_until ?? "", is_active: row.is_active });
  return <div className="space-y-6" data-testid="mass-timetable-page"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-serif text-2xl font-bold">Ratiba za Misa</h1><p className="text-sm text-muted-foreground">Ratiba za kila wiki na matukio yaliyotengenezwa.</p></div><div className="flex gap-2"><Button onClick={() => setForm(emptyForm())}><Plus className="mr-2 h-4 w-4"/>Ongeza</Button><Button variant="outline" onClick={() => generate.mutate()} disabled={generate.isPending}><RefreshCw className="mr-2 h-4 w-4"/>Tengeneza siku 90</Button></div></div>
    {timetable.isLoading ? <Loader2 className="mx-auto h-6 w-6 animate-spin"/> : timetable.isError ? <Card><CardContent className="p-6 text-destructive">Ratiba haikupatikana.</CardContent></Card> : <><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{timetable.data?.schedules.map(row => <Card key={row.id}><CardHeader><CardTitle className="flex justify-between gap-2 text-base"><span>{row.name}</span><Badge variant={row.is_active ? "default" : "secondary"}>{row.is_active ? "Inatumika" : "Imezimwa"}</Badge></CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>{MASS_WEEKDAYS[row.day_of_week]} · {formatMassTime(row.start_time)} · {row.location_name || "Kanisa kuu"}</p><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => openEdit(row)}>Hariri</Button><Button variant="outline" size="sm" onClick={() => toggle.mutate(row)}>{row.is_active ? "Zima" : "Washa"}</Button></div></CardContent></Card>)}</section><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="h-4 w-4"/>Misa zijazo</CardTitle></CardHeader><CardContent className="space-y-2">{timetable.data?.occurrences.length ? timetable.data.occurrences.map(row => <div key={row.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border p-3 text-sm"><span><strong>{row.name}</strong> · {formatMassDate(row.occurrence_date)} {formatMassTime(row.start_time)}</span><Badge variant={row.status === "cancelled" ? "destructive" : "outline"}>{row.status}</Badge></div>) : <p className="py-6 text-center text-muted-foreground">Hakuna Misa zijazo. Tumia kitufe cha kutengeneza.</p>}</CardContent></Card></>}
    <Dialog open={!!form} onOpenChange={open => !open && setForm(null)}><DialogContent><DialogHeader><DialogTitle>{form?.id ? "Hariri ratiba" : "Ratiba mpya"}</DialogTitle></DialogHeader>{form && <form className="grid gap-4 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); save.mutate(form); }}><Field label="Jina"><Input value={form.name} onChange={e => setForm({...form,name:e.target.value})}/></Field><Field label="Siku"><select className="h-10 w-full rounded-md border bg-background px-3" value={form.day_of_week} onChange={e => setForm({...form,day_of_week:e.target.value})}>{MASS_WEEKDAYS.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></Field><Field label="Muda wa kuanza"><Input type="time" value={form.start_time} onChange={e => setForm({...form,start_time:e.target.value})}/></Field><Field label="Muda wa mwisho"><Input type="time" value={form.end_time} onChange={e => setForm({...form,end_time:e.target.value})}/></Field><Field label="Mahali"><Input value={form.location_name} onChange={e => setForm({...form,location_name:e.target.value})}/></Field><Field label="Lugha"><Input value={form.language} onChange={e => setForm({...form,language:e.target.value})}/></Field><Field label="Uwezo wa nia"><Input type="number" min="0" value={form.intention_capacity} onChange={e => setForm({...form,intention_capacity:e.target.value})}/></Field><Field label="Ada ya nia"><Input type="number" min="0" value={form.default_intention_fee} onChange={e => setForm({...form,default_intention_fee:e.target.value})}/></Field><Field label="Kuanzia"><Input type="date" value={form.effective_from} onChange={e => setForm({...form,effective_from:e.target.value})}/></Field><Field label="Mpaka"><Input type="date" value={form.effective_until} onChange={e => setForm({...form,effective_until:e.target.value})}/></Field><div className="flex items-center gap-2"><Switch checked={form.accepts_intentions} onCheckedChange={v => setForm({...form,accepts_intentions:v})}/><Label>Inapokea nia</Label></div><Button className="sm:col-span-2" type="submit" disabled={save.isPending}>Hifadhi</Button></form>}</DialogContent></Dialog>
  </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
