import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Radio } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { useRadioPermission } from "@/hooks/use-church-radio";
import { fetchChurchRadioCatalogue, setChurchRadioSelection, type ChurchRadioCatalogueEntry } from "@/lib/church-radio";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

export default function RadioStationsPage(){const {churchId}=useAuth();const permission=useRadioPermission("manage");const client=useQueryClient();const key=["production-radio-catalogue",churchId];const catalogue=useQuery({queryKey:key,queryFn:()=>fetchChurchRadioCatalogue(churchId!),enabled:!!churchId&&permission.data===true});const save=useMutation({mutationFn:({station,enabled,isDefault=station.isDefault,sortOrder=station.sortOrder}:{station:ChurchRadioCatalogueEntry;enabled:boolean;isDefault?:boolean;sortOrder?:number})=>setChurchRadioSelection(churchId!,station.id,enabled,isDefault,sortOrder),onSuccess:()=>void client.invalidateQueries({queryKey:key})});if(permission.isLoading)return <div className="min-h-48 animate-pulse rounded-3xl bg-muted"/>;if(permission.data!==true)return <section data-testid="radio-admin-denied" className="rounded-2xl border p-8 text-center"><h1 className="text-xl font-bold">Radio management unavailable</h1><p className="mt-2 text-sm text-muted-foreground">This feature is disabled or you do not have permission.</p></section>;return <main className="mx-auto max-w-4xl space-y-6"><header><p className="text-xs font-bold tracking-widest text-red-500">RADIO</p><h1 className="mt-2 text-3xl font-bold">Member radio stations</h1><p className="mt-2 text-sm text-muted-foreground">Choose approved stations for this church. You cannot edit the central directory here.</p></header><div className="space-y-3">{catalogue.data?.map((station,index)=><Card key={station.id}><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><Radio className="h-7 w-7 shrink-0 text-red-500"/><div className="min-w-0 flex-1"><h2 className="font-bold">{station.name}</h2><p className="text-sm text-muted-foreground">{station.description||"Approved by Kanisa Connect"}</p></div><div className="flex flex-wrap gap-2"><Button disabled={save.isPending} variant={station.enabled?"default":"outline"} onClick={()=>save.mutate({station,enabled:!station.enabled,isDefault:false,sortOrder:station.sortOrder||index})}>{station.enabled?"Selected":"Select"}</Button><Button disabled={!station.enabled||save.isPending} variant={station.isDefault?"secondary":"outline"} onClick={()=>save.mutate({station,enabled:true,isDefault:true})}>{station.isDefault?"Default":"Make default"}</Button></div></CardContent></Card>)}{!catalogue.isLoading&&!catalogue.data?.length?<p className="rounded-2xl border border-dashed p-8 text-center text-muted-foreground">No approved stations are available.</p>:null}</div></main>}
