import { useQuery } from "@tanstack/react-query";
import { useAuth } from "@/contexts/AuthContext";
import { useFeatureAccess } from "@/hooks/use-feature-access";
import { fetchMemberLivestream, fetchMemberLivestreamById } from "@/lib/church-livestreams";
import { supabase } from "@/integrations/supabase/client";
export function useLivestreamPermission(action:"view"|"create"|"edit"|"delete"|"manage",enabled=true){const {churchId,user}=useAuth();return useQuery({queryKey:["production-livestream-permission",action,user?.id,churchId],queryFn:async()=>{const {data,error}=await supabase.rpc("has_livestream_permission" as never,{_user_id:user!.id,_church_id:churchId!,_action:action} as never);if(error)throw error;return data===true},enabled:!!user&&!!churchId&&enabled,staleTime:30000})}
function useLivestreamViewPermission(enabled:boolean){return useLivestreamPermission("view",enabled)}
export function useChurchLivestream(){ const {churchId}=useAuth(); const access=useFeatureAccess(); const feature=access.getFeatureState("livestream"); const featureEligible=access.isResolved&&feature.exists&&feature.visible; const permission=useLivestreamViewPermission(featureEligible); const enabled=featureEligible&&permission.data===true; const query=useQuery({queryKey:["production-livestream",churchId],queryFn:()=>fetchMemberLivestream(churchId!),enabled:!!churchId&&!access.isLoading&&!permission.isLoading&&enabled,staleTime:30000}); const gateError=access.error??permission.error??null; const refetch=()=>access.error?access.refetch():permission.isError?permission.refetch():query.refetch(); return {...query,data:enabled?query.data??null:null,error:gateError??query.error,isError:!!gateError||query.isError,refetch,featureEnabled:enabled,featureLoading:access.isLoading||(featureEligible&&permission.isLoading),churchId}; }
export function useMemberLivestream(streamId?:string){ const {churchId}=useAuth(); const access=useFeatureAccess(); const feature=access.getFeatureState("livestream"); const featureEligible=access.isResolved&&feature.exists&&feature.visible; const permission=useLivestreamViewPermission(featureEligible); const enabled=featureEligible&&permission.data===true; const query=useQuery({queryKey:["production-livestream",churchId,streamId],queryFn:()=>fetchMemberLivestreamById(churchId!,streamId!),enabled:!!churchId&&!!streamId&&!access.isLoading&&!permission.isLoading&&enabled,staleTime:30000}); const gateError=access.error??permission.error??null; const refetch=()=>access.error?access.refetch():permission.isError?permission.refetch():query.refetch(); return {...query,data:enabled?query.data??null:null,error:gateError??query.error,isError:!!gateError||query.isError,refetch,featureEnabled:enabled,featureLoading:access.isLoading||(featureEligible&&permission.isLoading),churchId}; }
