import type { AutomationRule } from "./types";

export const defaultAutomationRules: AutomationRule[] = [
  {
    id: "member-mass-tomorrow",
    title: "Member Mass Tomorrow Reminder",
    description: "Remind members when Mass is tomorrow.",
    eventTypes: ["MASS_TOMORROW"],
    workspaces: ["member"],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create Mass reminder",
        to: "/portal/calendar",
        assistantEvent: {
          title: "Mass tomorrow",
          detail: "You have a Mass on the parish calendar tomorrow.",
          priority: "medium",
          category: "liturgy",
          to: "/portal/calendar",
          actionLabel: "Open calendar",
        },
      },
      { id: "reminder", type: "SHOW_REMINDER", label: "Show Mass reminder", to: "/portal/calendar" },
    ],
  },
  {
    id: "member-prayer-approved",
    title: "Prayer Approved Notification",
    eventTypes: ["PRAYER_REQUEST_APPROVED"],
    workspaces: ["member"],
    actions: [
      {
        id: "notification",
        type: "CREATE_NOTIFICATION",
        label: "Create prayer notification",
        notification: { title: "Prayer request approved", body: "Your prayer request has been approved." },
      },
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create prayer assistant event",
        to: "/portal/prayer-requests",
        assistantEvent: {
          title: "Prayer request approved",
          detail: "Your prayer request status changed.",
          priority: "medium",
          category: "pastoral",
          to: "/portal/prayer-requests",
          actionLabel: "Track",
        },
      },
    ],
  },
  {
    id: "member-contribution-receipt",
    title: "Contribution Receipt Available",
    eventTypes: ["CONTRIBUTION_RECORDED"],
    workspaces: ["member"],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create receipt event",
        to: "/portal/contribution-history",
        assistantEvent: {
          title: "Contribution receipt available",
          detail: "A new contribution was recorded in your giving history.",
          priority: "info",
          category: "finance",
          to: "/portal/contribution-history",
          actionLabel: "Open receipt",
        },
      },
    ],
  },
  {
    id: "admin-announcement-expiring",
    title: "Announcement Expiring Tomorrow",
    eventTypes: ["ANNOUNCEMENT_EXPIRING"],
    workspaces: ["church_admin"],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create announcement reminder",
        to: "/church-admin/announcements",
        assistantEvent: {
          title: "Announcement expires tomorrow",
          detail: "Review or archive the announcement before it expires.",
          priority: "medium",
          category: "administration",
          to: "/church-admin/announcements",
          actionLabel: "Review",
        },
      },
      { id: "log", type: "LOG_AUTOMATION", label: "Log announcement expiry" },
    ],
  },
  {
    id: "admin-invitation-pending",
    title: "Invitation Pending Reminder",
    eventTypes: ["INVITATION_PENDING"],
    workspaces: ["church_admin"],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create invitation reminder",
        to: "/church-admin/roles",
        assistantEvent: {
          title: "Invitation pending",
          detail: "One or more invitations still need follow-up.",
          priority: "medium",
          category: "administration",
          to: "/church-admin/roles",
          actionLabel: "Open",
        },
      },
    ],
  },
  {
    id: "finance-outstanding-pledge",
    title: "Outstanding Pledge Reminder",
    eventTypes: ["PLEDGE_DUE"],
    workspaces: ["finance"],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create pledge reminder",
        to: "/finance/pledges",
        assistantEvent: {
          title: "Outstanding pledge",
          detail: "A pledge is due and needs finance follow-up.",
          priority: "high",
          category: "finance",
          to: "/finance/pledges",
          actionLabel: "Review",
        },
      },
    ],
  },
  {
    id: "finance-large-contribution",
    title: "Large Contribution Review",
    eventTypes: ["CONTRIBUTION_RECORDED"],
    workspaces: ["finance"],
    conditions: [{ kind: "contribution_amount", gte: 1000000 }],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create large contribution review",
        to: "/finance/contributions",
        assistantEvent: {
          title: "Large contribution received",
          detail: "A large contribution should be reviewed and reconciled.",
          priority: "high",
          category: "finance",
          to: "/finance/contributions",
          actionLabel: "Review",
        },
      },
      { id: "log", type: "LOG_AUTOMATION", label: "Log large contribution" },
    ],
  },
  {
    id: "pastoral-prayer-waiting-48h",
    title: "Prayer Request Waiting 48 Hours",
    eventTypes: ["PRAYER_REQUEST_PENDING"],
    workspaces: ["pastoral"],
    conditions: [{ kind: "waiting_time", field: "createdAt", gteHours: 48 }],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create high priority prayer event",
        to: "/pastoral/prayer-requests",
        assistantEvent: {
          title: "Prayer request waiting 48 hours",
          detail: "A prayer request has waited more than 48 hours.",
          priority: "high",
          category: "pastoral",
          to: "/pastoral/prayer-requests",
          actionLabel: "Review",
        },
      },
    ],
  },
  {
    id: "pastoral-mass-intentions-awaiting-scheduling",
    title: "Mass Intentions Awaiting Scheduling",
    eventTypes: ["MASS_INTENTION_CREATED"],
    workspaces: ["pastoral"],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create Mass intention reminder",
        to: "/pastoral/mass-intentions",
        assistantEvent: {
          title: "Mass intention needs scheduling",
          detail: "A new Mass intention is awaiting pastoral scheduling.",
          priority: "medium",
          category: "pastoral",
          to: "/pastoral/mass-intentions",
          actionLabel: "Schedule",
        },
      },
    ],
  },
  {
    id: "pastoral-sacrament-scheduled",
    title: "Sacrament Scheduled Reminder",
    eventTypes: ["SACRAMENT_SCHEDULED"],
    workspaces: ["pastoral"],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create sacrament schedule reminder",
        to: "/pastoral/sacraments",
        assistantEvent: {
          title: "Sacrament scheduled",
          detail: "A sacramental celebration or preparation session is on the pastoral calendar.",
          priority: "medium",
          category: "pastoral",
          to: "/pastoral/sacraments",
          actionLabel: "Open sacraments",
        },
      },
    ],
  },
  {
    id: "pastoral-sacrament-preparation",
    title: "Sacrament Preparation Reminder",
    eventTypes: ["SACRAMENT_PREPARATION_DUE"],
    workspaces: ["pastoral"],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create preparation reminder",
        to: "/pastoral/sacraments",
        assistantEvent: {
          title: "Sacramental preparation due",
          detail: "A preparation class or follow-up step needs pastoral attention.",
          priority: "high",
          category: "pastoral",
          to: "/pastoral/sacraments",
          actionLabel: "Review",
        },
      },
    ],
  },
  {
    id: "pastoral-sacrament-certificate-ready",
    title: "Sacrament Certificate Ready",
    eventTypes: ["SACRAMENT_CERTIFICATE_READY"],
    workspaces: ["pastoral", "church_admin"],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create certificate reminder",
        to: "/pastoral/sacraments",
        assistantEvent: {
          title: "Certificate ready",
          detail: "A sacramental certificate is ready to print or issue.",
          priority: "medium",
          category: "administration",
          to: "/pastoral/sacraments",
          actionLabel: "Print",
        },
      },
    ],
  },
  {
    id: "super-admin-platform-warning",
    title: "Platform Health Warning",
    eventTypes: ["PLATFORM_HEALTH_WARNING"],
    workspaces: ["super_admin"],
    actions: [
      {
        id: "assistant-event",
        type: "CREATE_ASSISTANT_EVENT",
        label: "Create critical platform event",
        to: "/super-admin/system-health",
        assistantEvent: {
          title: "Platform health warning",
          detail: "A platform health warning requires review.",
          priority: "critical",
          category: "platform",
          to: "/super-admin/system-health",
          actionLabel: "Review",
        },
      },
      { id: "log", type: "LOG_AUTOMATION", label: "Log platform warning" },
    ],
  },
];
