type BibleBookLike = {
  name: string;
};

const SWAHILI_BOOK_NAMES: Record<string, string> = {
  genesis: "Mwanzo",
  exodus: "Kutoka",
  leviticus: "Walawi",
  numbers: "Hesabu",
  deuteronomy: "Kumbukumbu la Torati",
  joshua: "Yoshua",
  judges: "Waamuzi",
  ruth: "Ruthu",
  "1 samuel": "1 Samweli",
  "2 samuel": "2 Samweli",
  "1 kings": "1 Wafalme",
  "2 kings": "2 Wafalme",
  "1 chronicles": "1 Mambo ya Nyakati",
  "2 chronicles": "2 Mambo ya Nyakati",
  ezra: "Ezra",
  nehemiah: "Nehemia",
  tobit: "Tobiti",
  judith: "Yudithi",
  esther: "Esta",
  job: "Ayubu",
  psalms: "Zaburi",
  proverbs: "Methali",
  ecclesiastes: "Mhubiri",
  "song of songs": "Wimbo Ulio Bora",
  wisdom: "Hekima",
  sirach: "Yoshua bin Sira",
  isaiah: "Isaya",
  jeremiah: "Yeremia",
  lamentations: "Maombolezo",
  baruch: "Baruku",
  ezekiel: "Ezekieli",
  daniel: "Danieli",
  hosea: "Hosea",
  joel: "Yoeli",
  amos: "Amosi",
  obadiah: "Obadia",
  jonah: "Yona",
  micah: "Mika",
  nahum: "Nahumu",
  habakkuk: "Habakuki",
  zephaniah: "Sefania",
  haggai: "Hagai",
  zechariah: "Zekaria",
  malachi: "Malaki",
  "1 maccabees": "1 Wamakabayo",
  "2 maccabees": "2 Wamakabayo",
  matthew: "Mathayo",
  mark: "Marko",
  luke: "Luka",
  john: "Yohana",
  acts: "Matendo ya Mitume",
  romans: "Waroma",
  "1 corinthians": "1 Wakorintho",
  "2 corinthians": "2 Wakorintho",
  galatians: "Wagalatia",
  ephesians: "Waefeso",
  philippians: "Wafilipi",
  colossians: "Wakolosai",
  "1 thessalonians": "1 Wathesalonike",
  "2 thessalonians": "2 Wathesalonike",
  "1 timothy": "1 Timotheo",
  "2 timothy": "2 Timotheo",
  titus: "Tito",
  philemon: "Filemoni",
  hebrews: "Waebrania",
  james: "Yakobo",
  "1 peter": "1 Petro",
  "2 peter": "2 Petro",
  "1 john": "1 Yohana",
  "2 john": "2 Yohana",
  "3 john": "3 Yohana",
  jude: "Yuda",
  revelation: "Ufunuo",
};

function normalizeBookName(name: string) {
  return name.toLowerCase().replace(/\s+/g, " ").trim();
}

export function getBibleBookDisplayName(book: BibleBookLike | null | undefined, language: string) {
  if (!book?.name) return "";
  if (!language.toLowerCase().startsWith("sw")) return book.name;
  return SWAHILI_BOOK_NAMES[normalizeBookName(book.name)] ?? book.name;
}

