import { supabase } from "@/integrations/supabase/client";

export type ChurchLivestream = { id:string; churchId:string; status:"scheduled"|"live"|"ended"|"cancelled"; title:string; provider:"youtube"; watchUrl:string; providerExternalId:string; scheduledStart:string|null; scheduledEnd:string|null; actualStartedAt:string|null; actualEndedAt:string|null };
type Row = { id:string; church_id:string; status:ChurchLivestream["status"]; title:string; provider:"youtube"; watch_url:string; provider_external_id:string; scheduled_start:string|null; scheduled_end:string|null; actual_started_at:string|null; actual_ended_at:string|null };
const db = supabase as unknown as { from:(table:string)=>any };
const ID = /^[A-Za-z0-9_-]{11}$/;
export const normalizeChurchLivestream = (row:Row):ChurchLivestream => ({ id:row.id, churchId:row.church_id, status:row.status, title:row.title, provider:row.provider, watchUrl:row.watch_url, providerExternalId:row.provider_external_id, scheduledStart:row.scheduled_start, scheduledEnd:row.scheduled_end, actualStartedAt:row.actual_started_at, actualEndedAt:row.actual_ended_at });
export function extractYouTubeVideoId(value:string) { try { const url=new URL(value); const host=url.hostname.toLowerCase().replace(/^www\./,""); let id:string|null=null; if(host==="youtu.be") id=url.pathname.split("/").filter(Boolean)[0]??null; else if(host==="youtube.com"||host==="m.youtube.com") id=url.pathname==="/watch"?url.searchParams.get("v"):["live","embed"].includes(url.pathname.split("/").filter(Boolean)[0])?url.pathname.split("/").filter(Boolean)[1]??null:null; return id&&ID.test(id)?id:null; } catch { return null; } }
export const getYouTubeEmbedUrl=(stream:ChurchLivestream)=>stream.provider==="youtube"&&ID.test(stream.providerExternalId)&&extractYouTubeVideoId(stream.watchUrl)===stream.providerExternalId?`https://www.youtube.com/embed/${stream.providerExternalId}`:null;
export const presentation=(stream:ChurchLivestream|null)=>stream?.status==="live"?"live":stream?.status==="scheduled"&&stream.scheduledStart&&new Date(stream.scheduledStart).getTime()-Date.now()>=0&&new Date(stream.scheduledStart).getTime()-Date.now()<=1_800_000?"upcoming":null;
export async function fetchMemberLivestream(churchId:string) { const {data,error}=await db.from("church_livestreams").select("*").eq("church_id",churchId).in("status",["live","scheduled"]).order("created_at",{ascending:false}); if(error) throw error; const rows=(data??[]).map(normalizeChurchLivestream); return rows.find((x)=>x.status==="live")??rows.filter((x)=>x.status==="scheduled").sort((a,b)=>String(a.scheduledStart).localeCompare(String(b.scheduledStart)))[0]??null; }
export async function fetchMemberLivestreamById(churchId:string,id:string) { const {data,error}=await db.from("church_livestreams").select("*").eq("church_id",churchId).eq("id",id).maybeSingle(); if(error) throw error; return data?normalizeChurchLivestream(data):null; }
