import type { ChurchPermissionAction } from "@/hooks/use-church-permission";

export type WorkspaceRoutePermission = {
  path: string;
  featureKey: string;
  action: ChurchPermissionAction;
};

// Explicit route metadata is the source of truth for direct-URL protection.
// Longest paths win, so detail and workflow routes cannot inherit a weaker rule.
export const WORKSPACE_ROUTE_PERMISSIONS: WorkspaceRoutePermission[] = ([
  { path: "/church-admin/settings/features-permissions", featureKey: "feature_permissions_admin", action: "manage" },
  { path: "/church-admin/events/", featureKey: "events", action: "view" },
  { path: "/church-admin/audio", featureKey: "audio_processing", action: "manage" },
  { path: "/church-admin/members", featureKey: "members", action: "view" },
  { path: "/church-admin/contributions", featureKey: "contributions", action: "view" },
  { path: "/church-admin/finance", featureKey: "contributions", action: "view" },
  { path: "/church-admin/qr-payments", featureKey: "give", action: "view" },
  { path: "/church-admin/pledges", featureKey: "pledges", action: "view" },
  { path: "/church-admin/communities", featureKey: "communities", action: "view" },
  { path: "/church-admin/ministries", featureKey: "ministries", action: "view" },
  { path: "/church-admin/families", featureKey: "families", action: "view" },
  { path: "/church-admin/events", featureKey: "events", action: "view" },
  { path: "/church-admin/calendar", featureKey: "events", action: "view" },
  { path: "/church-admin/mass-schedule", featureKey: "events", action: "view" },
  { path: "/church-admin/event-requests", featureKey: "event_requests", action: "view" },
  { path: "/church-admin/announcements", featureKey: "announcements", action: "view" },
  { path: "/church-admin/sermons", featureKey: "sermons", action: "view" },
  { path: "/church-admin/livestreams", featureKey: "livestream", action: "manage" },
  { path: "/church-admin/radio", featureKey: "radio", action: "manage" },
  { path: "/church-admin/bible-verses", featureKey: "bible_verses", action: "view" },
  { path: "/church-admin/bible", featureKey: "bible_verses", action: "view" },
  { path: "/church-admin/daily-readings", featureKey: "catholic_content", action: "view" },
  { path: "/church-admin/saints", featureKey: "catholic_content", action: "view" },
  { path: "/church-admin/library", featureKey: "catholic_content", action: "view" },
  { path: "/church-admin/prayers", featureKey: "catholic_content", action: "view" },
  { path: "/church-admin/prayer-requests", featureKey: "prayer_requests", action: "view" },
  { path: "/church-admin/mass-intentions", featureKey: "mass_intentions", action: "view" },
  { path: "/church-admin/mass-timetable", featureKey: "mass_intentions", action: "view" },
  { path: "/church-admin/community-help", featureKey: "community_help", action: "view" },
  { path: "/church-admin/notifications", featureKey: "notifications", action: "view" },
  { path: "/church-admin/channels", featureKey: "channels", action: "view" },
  { path: "/church-admin/roles", featureKey: "feature_permissions_admin", action: "manage" },
  { path: "/church-admin/settings", featureKey: "feature_permissions_admin", action: "manage" },
  { path: "/church-admin/reports", featureKey: "reports", action: "view" },
  { path: "/church-admin/analytics", featureKey: "reports", action: "view" },
  { path: "/church-admin/finance-intelligence", featureKey: "finance_intelligence", action: "view" },
  { path: "/church-admin/analytics-assistant", featureKey: "finance_intelligence", action: "view" },
  { path: "/church-admin/kanisa-ai", featureKey: "kanisa_ai", action: "view" },
  { path: "/church-admin/operations", featureKey: "operations", action: "view" },
  { path: "/church-admin/data-import", featureKey: "members", action: "manage" },
  { path: "/church-admin/audit-logs", featureKey: "reports", action: "view" },
  { path: "/pastoral/mass-intentions", featureKey: "mass_intentions", action: "view" },
  { path: "/pastoral/dashboard", featureKey: "catholic_content", action: "view" },
  { path: "/pastoral/prayer-requests", featureKey: "prayer_requests", action: "view" },
  { path: "/pastoral/community-help", featureKey: "community_help", action: "view" },
  { path: "/pastoral/mass-schedule", featureKey: "events", action: "view" },
  { path: "/pastoral/events", featureKey: "events", action: "view" },
  { path: "/pastoral/announcements", featureKey: "announcements", action: "view" },
  { path: "/pastoral/contributions", featureKey: "contributions", action: "view" },
  { path: "/pastoral/sacraments", featureKey: "sacraments", action: "view" },
  { path: "/pastoral/kanisa-ai", featureKey: "kanisa_ai", action: "view" },
  { path: "/pastoral/calendar", featureKey: "events", action: "view" },
  { path: "/pastoral/bible", featureKey: "bible_verses", action: "view" },
  { path: "/pastoral/liturgy", featureKey: "catholic_content", action: "view" },
  { path: "/pastoral/daily-readings", featureKey: "catholic_content", action: "view" },
  { path: "/pastoral/saints", featureKey: "catholic_content", action: "view" },
  { path: "/pastoral/library", featureKey: "catholic_content", action: "view" },
  { path: "/pastoral/liturgical-calendar", featureKey: "catholic_content", action: "view" },
  { path: "/pastoral/prayers", featureKey: "catholic_content", action: "view" },
  { path: "/finance/contributions", featureKey: "contributions", action: "view" },
  { path: "/finance/receipts", featureKey: "contributions", action: "view" },
  { path: "/finance/pledges", featureKey: "pledges", action: "view" },
  { path: "/finance/community-help", featureKey: "community_help", action: "view" },
  { path: "/finance/reports", featureKey: "reports", action: "view" },
  { path: "/finance/exports", featureKey: "reports", action: "manage" },
  { path: "/finance/finance-intelligence", featureKey: "finance_intelligence", action: "view" },
  { path: "/finance/kanisa-ai", featureKey: "kanisa_ai", action: "view" },
  { path: "/finance/calendar", featureKey: "events", action: "view" },
  { path: "/finance/bible", featureKey: "bible_verses", action: "view" },
  { path: "/finance/daily-readings", featureKey: "catholic_content", action: "view" },
  { path: "/finance/saints", featureKey: "catholic_content", action: "view" },
  { path: "/finance/library", featureKey: "catholic_content", action: "view" },
  { path: "/finance/settings", featureKey: "feature_permissions_admin", action: "manage" },
  { path: "/portal/contribution-receipt/", featureKey: "contributions", action: "view" },
  { path: "/portal/contribution-history", featureKey: "contributions", action: "view" },
  { path: "/portal/give", featureKey: "give", action: "view" },
  { path: "/portal/pledges", featureKey: "pledges", action: "view" },
  { path: "/portal/events", featureKey: "events", action: "view" },
  { path: "/portal/calendar", featureKey: "events", action: "view" },
  { path: "/portal/event-requests", featureKey: "event_requests", action: "view" },
  { path: "/portal/announcements", featureKey: "announcements", action: "view" },
  { path: "/portal/sermons", featureKey: "sermons", action: "view" },
  { path: "/portal/prayer-requests", featureKey: "prayer_requests", action: "view" },
  { path: "/portal/mass-intentions", featureKey: "mass_intentions", action: "view" },
  { path: "/portal/ministries", featureKey: "ministries", action: "view" },
  { path: "/portal/community-help", featureKey: "community_help", action: "view" },
  { path: "/portal/channels", featureKey: "channels", action: "view" },
  { path: "/portal/kanisa-ai", featureKey: "kanisa_ai", action: "view" },
  { path: "/portal/bible-verses", featureKey: "bible_verses", action: "view" },
  { path: "/portal/bible", featureKey: "bible_verses", action: "view" },
  { path: "/portal/prayers", featureKey: "catholic_content", action: "view" },
  { path: "/portal/reflections", featureKey: "catholic_content", action: "view" },
  { path: "/portal/library", featureKey: "catholic_content", action: "view" },
  { path: "/portal/saints", featureKey: "catholic_content", action: "view" },
  { path: "/portal/liturgical-calendar", featureKey: "catholic_content", action: "view" },
  { path: "/portal/daily-readings", featureKey: "catholic_content", action: "view" },
] satisfies WorkspaceRoutePermission[]).sort((left, right) => right.path.length - left.path.length);

export function getWorkspaceRoutePermission(pathname: string) {
  return WORKSPACE_ROUTE_PERMISSIONS.find(({ path }) => pathname === path || pathname.startsWith(`${path}/`) || (path.endsWith("/") && pathname.startsWith(path))) ?? null;
}
