import { createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,type ReactNode } from "react";
import { useLocation,useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { useMemberLivestream } from "@/hooks/use-church-livestream";
import { useLiveMediaCoordinator } from "@/contexts/LiveMediaCoordinator";
const Context=createContext<any>(null);
const routeId=(path:string)=>path.match(/^\/(?:portal|member)\/live\/([^/]+)\/?$/)?.[1]??null;
export function PersistentLivestreamProvider({children}:{children:ReactNode}){ const navigate=useNavigate(),location=useLocation(); const media=useLiveMediaCoordinator(); const {churchId,user}=useAuth(); const [activeStreamId,setId]=useState<string|null>(null); const [mode,setMode]=useState<"closed"|"full"|"mini">("closed"); const scope=useRef({churchId,user:user?.id}); const query=useMemberLivestream(activeStreamId??undefined); const close=useCallback(()=>{setId(null);setMode("closed")},[]); useEffect(()=>media.register("livestream",close),[media,close]); useEffect(()=>{if(scope.current.churchId!==churchId||scope.current.user!==user?.id)close();scope.current={churchId,user:user?.id}},[churchId,user?.id,close]); useEffect(()=>{if(activeStreamId)setMode(routeId(location.pathname)===activeStreamId?"full":"mini")},[activeStreamId,location.pathname]); useEffect(()=>{if(activeStreamId&&!query.featureLoading&&(!query.featureEnabled||query.error||query.data&&query.data.churchId!==churchId))close()},[activeStreamId,query.featureLoading,query.featureEnabled,query.error,query.data,churchId,close]); const open=useCallback((id:string)=>{media.activate("livestream");setId(id);setMode("full");navigate(`/portal/live/${encodeURIComponent(id)}`)},[media,navigate]); const expand=useCallback(()=>activeStreamId&&navigate(`/portal/live/${encodeURIComponent(activeStreamId)}`),[activeStreamId,navigate]); const value=useMemo(()=>({activeStreamId,mode,stream:query.data,featureEnabled:query.featureEnabled,churchId,open,expand,close}),[activeStreamId,mode,query.data,query.featureEnabled,churchId,open,expand,close]);return <Context.Provider value={value}>{children}</Context.Provider>}
export const usePersistentLivestream=()=>{const v=useContext(Context);if(!v)throw new Error("PersistentLivestreamProvider required");return v};
export const useOptionalPersistentLivestream=()=>useContext(Context);
