export type PrayerStatus = "draft" | "review" | "published" | "featured" | "archived";
export type PrayerType = "single" | "collection" | "section" | "litany" | "rosary" | "stations_of_cross" | "mass_collection";
export type PrayerSourceType = "roman_missal" | "catechism" | "bishops_conference" | "diocesan_publication" | "parish_publication" | "approved_prayer_book" | "scripture" | "public_domain" | "original_parish_content" | "user_submitted" | "other";
export type PrayerLicenseType = "public_domain" | "permission_granted" | "licensed" | "attribution_required" | "internal_church_use" | "copyright_restricted" | "unknown";
export type EcclesialApprovalStatus = "pending" | "under_review" | "approved" | "rejected" | "revision_required";

export type PrayerCategory = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  icon: string | null;
  sort_order: number;
  is_active: boolean;
  published_count?: number;
};

export type PrayerSummary = {
  id: string;
  prayer_code: string | null;
  parent_prayer_id: string | null;
  title: string;
  slug: string;
  summary: string | null;
  category_id: string | null;
  language_id: string | null;
  status: PrayerStatus;
  featured: boolean;
  prayer_type: PrayerType;
  recommended_time: string | null;
  audio_url: string | null;
  sort_order: number;
  is_global: boolean;
  church_id: string | null;
  liturgical_season: string | null;
  scripture_reference: string | null;
  updated_at: string;
  translation_group_id: string;
  translation_key: string | null;
  category?: Pick<PrayerCategory, "id" | "name" | "slug" | "icon"> | null;
  language?: { id: string; code: string; name: string; native_name: string | null } | null;
};

export type PrayerDetail = PrayerSummary & {
  body: string | null;
  metadata: Record<string, unknown>;
  source: string | null;
  source_title: string | null;
  source_type: PrayerSourceType | null;
  source_organization: string | null;
  source_reference: string | null;
  source_url: string | null;
  source_notes: string | null;
  copyright_holder: string | null;
  copyright_notice: string | null;
  license_type: PrayerLicenseType | null;
  license_reference: string | null;
  content_edition: string | null;
  content_version_label: string | null;
  ecclesial_approval_status: EcclesialApprovalStatus;
  ecclesial_approval_authority: string | null;
  ecclesial_approval_reference: string | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
};

export type PrayerAdminInput = {
  title: string;
  slug: string;
  summary: string;
  body: string;
  category_id: string;
  parent_prayer_id: string | null;
  language_id: string;
  status: PrayerStatus;
  prayer_type: PrayerType;
  recommended_time: string;
  scripture_reference: string;
  liturgical_season: string;
  featured: boolean;
  sort_order: number;
  audio_url: string;
  source_title: string;
  source_type: PrayerSourceType | "";
  source_organization: string;
  source_reference: string;
  source_url: string;
  source_notes: string;
  copyright_holder: string;
  copyright_notice: string;
  license_type: PrayerLicenseType | "";
  license_reference: string;
  content_edition: string;
  content_version_label: string;
  ecclesial_approval_status: EcclesialApprovalStatus;
  ecclesial_approval_authority: string;
  ecclesial_approval_reference: string;
  reviewed_by: string;
  reviewed_at: string;
};
