-- Add bounded recurrence metadata for parish events.
-- Occurrences are generated by the calendar engine; this migration does not
-- create duplicate event rows for each occurrence.

alter table public.events
  add column if not exists recurrence_frequency text not null default 'none',
  add column if not exists recurrence_interval integer not null default 1,
  add column if not exists recurrence_days_of_week integer[],
  add column if not exists recurrence_end_date date,
  add column if not exists recurrence_count integer,
  add column if not exists recurrence_monthly_pattern text not null default 'day_of_month',
  add column if not exists recurrence_monthly_week integer,
  add column if not exists recurrence_monthly_weekday integer;

alter table public.events
  drop constraint if exists events_recurrence_frequency_check,
  add constraint events_recurrence_frequency_check
    check (recurrence_frequency in ('none', 'daily', 'weekly', 'monthly')),
  drop constraint if exists events_recurrence_interval_check,
  add constraint events_recurrence_interval_check
    check (recurrence_interval >= 1 and recurrence_interval <= 366),
  drop constraint if exists events_recurrence_days_of_week_check,
  add constraint events_recurrence_days_of_week_check
    check (
      recurrence_days_of_week is null
      or (
        array_length(recurrence_days_of_week, 1) >= 1
        and recurrence_days_of_week <@ array[0,1,2,3,4,5,6]
      )
    ),
  drop constraint if exists events_recurrence_count_check,
  add constraint events_recurrence_count_check
    check (recurrence_count is null or (recurrence_count >= 1 and recurrence_count <= 1000)),
  drop constraint if exists events_recurrence_monthly_pattern_check,
  add constraint events_recurrence_monthly_pattern_check
    check (recurrence_monthly_pattern in ('day_of_month', 'nth_weekday')),
  drop constraint if exists events_recurrence_monthly_week_check,
  add constraint events_recurrence_monthly_week_check
    check (recurrence_monthly_week is null or recurrence_monthly_week between 1 and 5),
  drop constraint if exists events_recurrence_monthly_weekday_check,
  add constraint events_recurrence_monthly_weekday_check
    check (recurrence_monthly_weekday is null or recurrence_monthly_weekday between 0 and 6),
  drop constraint if exists events_recurrence_end_check,
  add constraint events_recurrence_end_check
    check (
      recurrence_frequency = 'none'
      or recurrence_end_date is not null
      or recurrence_count is not null
    );

create index if not exists idx_events_church_recurrence
  on public.events (church_id, recurrence_frequency, recurrence_end_date);

