import { act, useEffect } from "react";
import { createRoot, type Root } from "react-dom/client";
import { beforeEach, afterEach, describe, expect, it, vi } from "vitest";
const state=vi.hoisted(()=>({auth:{churchId:"church-a",user:{id:"user-a"} as {id:string}|null},stations:[{id:"one",name:"Radio One",streamUrl:"https://radio.example/one",websiteUrl:null,logoUrl:null,description:null,isActive:true,isApproved:true,selectionId:"s1",churchId:"church-a",enabled:true,isDefault:true,sortOrder:0},{id:"two",name:"Radio Two",streamUrl:"https://radio.example/two",websiteUrl:null,logoUrl:null,description:null,isActive:true,isApproved:true,selectionId:"s2",churchId:"church-a",enabled:true,isDefault:false,sortOrder:1}]}));
vi.mock("@/contexts/AuthContext",()=>({useAuth:()=>state.auth}));
vi.mock("@/hooks/use-church-radio",()=>({useChurchRadioStations:()=>({data:state.stations,featureEnabled:true,featureLoading:false})}));
import { LiveMediaCoordinatorProvider,useLiveMediaCoordinator } from "@/contexts/LiveMediaCoordinator";
import { RadioPlayerProvider,useRadioPlayer } from "@/contexts/RadioPlayerContext";
import { PersistentRadioPlayer } from "@/components/portal/PersistentRadioPlayer";
const stopLivestream=vi.fn();
function LivestreamStub(){const media=useLiveMediaCoordinator();useEffect(()=>media.register("livestream",stopLivestream),[media]);return null}

function Harness(){const radio=useRadioPlayer();const media=useLiveMediaCoordinator();return <><button onClick={()=>void radio.play(state.stations[0])}>one</button><button onClick={()=>void radio.play(state.stations[1])}>two</button><button onClick={radio.pause}>pause</button><button onClick={radio.close}>close</button><button onClick={()=>media.activate("livestream")}>livestream</button><output>{radio.state}:{radio.station?.id??"none"}</output></>}
describe("Wave 5A persistent Radio playback",()=>{let host:HTMLDivElement;let root:Root;let play:ReturnType<typeof vi.spyOn>;let pause:ReturnType<typeof vi.spyOn>;const render=()=>act(()=>root.render(<LiveMediaCoordinatorProvider><LivestreamStub/><RadioPlayerProvider><Harness/><PersistentRadioPlayer/></RadioPlayerProvider></LiveMediaCoordinatorProvider>));beforeEach(()=>{state.auth={churchId:"church-a",user:{id:"user-a"}};stopLivestream.mockReset();host=document.createElement("div");document.body.append(host);root=createRoot(host);play=vi.spyOn(HTMLMediaElement.prototype,"play").mockResolvedValue();pause=vi.spyOn(HTMLMediaElement.prototype,"pause").mockImplementation(()=>{});vi.spyOn(HTMLMediaElement.prototype,"load").mockImplementation(()=>{});render()});afterEach(()=>{act(()=>root.unmount());host.remove();vi.restoreAllMocks()});
  it("plays, pauses, switches, persists as one audio element, closes, and reopens",async()=>{const buttons=host.querySelectorAll<HTMLButtonElement>("button");await act(async()=>buttons[0].click());expect(host.textContent).toContain("playing:one");expect(host.querySelectorAll("audio")).toHaveLength(1);await act(async()=>buttons[2].click());expect(host.textContent).toContain("paused:one");await act(async()=>buttons[1].click());expect(host.textContent).toContain("playing:two");expect(host.querySelectorAll("audio")).toHaveLength(1);act(()=>buttons[3].click());expect(host.textContent).toContain("closed:none");await act(async()=>buttons[0].click());expect(host.textContent).toContain("playing:one");expect(play).toHaveBeenCalledTimes(3)});
  it("stops Radio before livestream activation",async()=>{const buttons=host.querySelectorAll<HTMLButtonElement>("button");await act(async()=>buttons[0].click());act(()=>buttons[4].click());expect(host.textContent).toContain("paused:one");expect(pause).toHaveBeenCalled()});
  it("stops livestream before Radio begins",async()=>{await act(async()=>host.querySelectorAll<HTMLButtonElement>("button")[0].click());expect(stopLivestream).toHaveBeenCalledTimes(1)});
  it("clears on logout and tenant change",async()=>{const buttons=host.querySelectorAll<HTMLButtonElement>("button");await act(async()=>buttons[0].click());state.auth={churchId:"church-b",user:{id:"user-b"}};render();expect(host.textContent).toContain("closed:none");await act(async()=>host.querySelectorAll<HTMLButtonElement>("button")[0].click());state.auth={churchId:null,user:null};render();expect(host.textContent).toContain("closed:none")});
});
