import { act } from "react";
import { createRoot } from "react-dom/client";
import { MemoryRouter,Route,Routes,useNavigate } from "react-router-dom";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
const state=vi.hoisted(()=>({auth:{churchId:"church-a",user:{id:"user-a"}},stream:{id:"stream-a",churchId:"church-a",status:"live",title:"UAT",provider:"youtube",watchUrl:"https://youtube.com/watch?v=M7lc1UVf-VE",providerExternalId:"M7lc1UVf-VE",scheduledStart:null,scheduledEnd:null,actualStartedAt:null,actualEndedAt:null}}));
vi.mock("@/contexts/AuthContext",()=>({useAuth:()=>state.auth}));
vi.mock("@/hooks/use-church-livestream",()=>({useMemberLivestream:(id?:string)=>({data:id?state.stream:null,error:null,featureEnabled:true,featureLoading:false})}));
import { PersistentLivestreamProvider,usePersistentLivestream } from "@/contexts/PersistentLivestreamContext";
import { PersistentLivestreamPlayer } from "@/components/portal/PersistentLivestreamPlayer";
import { AppLink } from "@/components/AppLink";
function Controls(){const p=usePersistentLivestream(),navigate=useNavigate();return <><button onClick={()=>p.open("stream-a")}>Open</button><button onClick={()=>navigate("/portal/announcements")}>Browse</button><button onClick={p.expand}>Expand</button><button onClick={()=>navigate(-1)}>Back</button><button onClick={p.close}>Close</button><AppLink to="/portal">Home</AppLink><AppLink to="/portal/services">Services</AppLink></>}
describe("production persistent player",()=>{let host:HTMLDivElement,root:ReturnType<typeof createRoot>;const render=()=>act(()=>root.render(<MemoryRouter initialEntries={["/portal"]}><PersistentLivestreamProvider><Controls/><Routes><Route path="*" element={<div/>}/></Routes><PersistentLivestreamPlayer/></PersistentLivestreamProvider></MemoryRouter>));beforeEach(()=>{state.auth={churchId:"church-a",user:{id:"user-a"}};host=document.createElement("div");document.body.append(host);root=createRoot(host);render()});afterEach(()=>{act(()=>root.unmount());host.remove()});it("preserves one iframe through full, mini, expand, and Back, then closes",()=>{act(()=>host.querySelector<HTMLButtonElement>("button")!.click());expect(host.querySelector('[data-player-mode="full"]')).not.toBeNull();expect(host.querySelectorAll("iframe")).toHaveLength(1);const iframe=host.querySelector("iframe");act(()=>host.querySelectorAll<HTMLButtonElement>("button")[1].click());expect(host.querySelector('[data-player-mode="mini"]')).not.toBeNull();expect(host.querySelector("iframe")).toBe(iframe);act(()=>host.querySelectorAll<HTMLButtonElement>("button")[2].click());expect(host.querySelector('[data-player-mode="full"]')).not.toBeNull();act(()=>host.querySelectorAll<HTMLButtonElement>("button")[3].click());expect(host.querySelector('[data-player-mode="mini"]')).not.toBeNull();expect(host.querySelector("iframe")).toBe(iframe);act(()=>host.querySelectorAll<HTMLButtonElement>("button")[4].click());expect(host.querySelectorAll("iframe")).toHaveLength(0)});it("preserves one iframe through shared AppLink route transitions",()=>{act(()=>host.querySelector<HTMLButtonElement>("button")!.click());const iframe=host.querySelector("iframe");act(()=>host.querySelectorAll<HTMLAnchorElement>("a")[0].click());expect(host.querySelector('[data-player-mode="mini"]')).not.toBeNull();expect(host.querySelector("iframe")).toBe(iframe);act(()=>host.querySelectorAll<HTMLAnchorElement>("a")[1].click());expect(host.querySelectorAll("iframe")).toHaveLength(1);expect(host.querySelector("iframe")).toBe(iframe)});it("clears playback when the authenticated user logs out",()=>{act(()=>host.querySelector<HTMLButtonElement>("button")!.click());state.auth={churchId:null,user:null};render();expect(host.querySelectorAll("iframe")).toHaveLength(0)});it("clears playback when user or tenant scope changes",()=>{act(()=>host.querySelector<HTMLButtonElement>("button")!.click());state.auth={churchId:"church-b",user:{id:"user-b"}};render();expect(host.querySelectorAll("iframe")).toHaveLength(0)})});
