import { act, useEffect } from "react";
import { createRoot, type Root } from "react-dom/client";
import { beforeEach, afterEach, describe, expect, it, vi } from "vitest";
import { MemoryRouter, Route, Routes, useLocation } from "react-router-dom";
const state=vi.hoisted(()=>({auth:{churchId:"church-a",user:{id:"user-a"} as {id:string}|null},featureEnabled:true,permissionGranted:true,stations:[{id:"one",name:"Radio One",streamUrl:"https://radio.example/one",websiteUrl:null,logoUrl:null,description:null,isActive:true,isApproved:true,selectionId:"s1",churchId:"church-a",enabled:true,isDefault:true,sortOrder:0},{id:"two",name:"Radio Two",streamUrl:"https://radio.example/two",websiteUrl:null,logoUrl:null,description:null,isActive:true,isApproved:true,selectionId:"s2",churchId:"church-a",enabled:true,isDefault:false,sortOrder:1}]}));
vi.mock("@/contexts/AuthContext",()=>({useAuth:()=>state.auth}));
vi.mock("@/hooks/use-church-radio",()=>({useChurchRadioStations:()=>({data:state.featureEnabled&&state.permissionGranted?state.stations:[],featureEnabled:state.featureEnabled&&state.permissionGranted,featureLoading:false})}));
import { LiveMediaCoordinatorProvider,useLiveMediaCoordinator } from "@/contexts/LiveMediaCoordinator";
import { RadioPlayerProvider,useRadioPlayer } from "@/contexts/RadioPlayerContext";
import { PersistentRadioPlayer } from "@/components/portal/PersistentRadioPlayer";
import { AppLink } from "@/components/AppLink";
const stopLivestream=vi.fn();
function LivestreamStub(){const media=useLiveMediaCoordinator();useEffect(()=>media.register("livestream",stopLivestream),[media]);return null}

function Harness(){const radio=useRadioPlayer();const media=useLiveMediaCoordinator();const location=useLocation();return <><button onClick={()=>void radio.play(state.stations[0])}>one</button><button onClick={()=>void radio.play(state.stations[1])}>two</button><button onClick={radio.pause}>pause</button><button onClick={radio.close}>close</button><button onClick={()=>media.activate("livestream")}>livestream</button><AppLink to="/portal">home</AppLink><AppLink to="/portal/services">services</AppLink><AppLink to="/portal/notifications">notifications</AppLink><output>{location.pathname}:{radio.state}:{radio.station?.id??"none"}</output></>}
describe("Wave 5A persistent Radio playback",()=>{let host:HTMLDivElement;let root:Root;let play:ReturnType<typeof vi.spyOn>;let pause:ReturnType<typeof vi.spyOn>;const render=()=>act(()=>root.render(<MemoryRouter initialEntries={["/portal/radio"]}><LiveMediaCoordinatorProvider><LivestreamStub/><RadioPlayerProvider><Harness/><Routes><Route path="*" element={<div/>}/></Routes><PersistentRadioPlayer/></RadioPlayerProvider></LiveMediaCoordinatorProvider></MemoryRouter>));beforeEach(()=>{state.auth={churchId:"church-a",user:{id:"user-a"}};state.featureEnabled=true;state.permissionGranted=true;stopLivestream.mockReset();host=document.createElement("div");document.body.append(host);root=createRoot(host);play=vi.spyOn(HTMLMediaElement.prototype,"play").mockResolvedValue();pause=vi.spyOn(HTMLMediaElement.prototype,"pause").mockImplementation(()=>{});vi.spyOn(HTMLMediaElement.prototype,"load").mockImplementation(()=>{});render()});afterEach(()=>{act(()=>root.unmount());host.remove();vi.restoreAllMocks()});
  it("does not create Radio media or a player shell while the feature is disabled",()=>{state.featureEnabled=false;render();expect(host.querySelectorAll('[data-testid="persistent-radio-audio"], audio')).toHaveLength(0);expect(host.querySelector('[data-testid="persistent-radio-player"]')).toBeNull();expect(host.textContent).toContain("closed:none")});
  it("stops playback and removes stale media when the feature becomes disabled",async()=>{await act(async()=>host.querySelectorAll<HTMLButtonElement>("button")[0].click());expect(host.textContent).toContain("playing:one");state.featureEnabled=false;render();expect(host.querySelectorAll("audio")).toHaveLength(0);expect(host.textContent).toContain("closed:none");expect(pause).toHaveBeenCalled()});
  it("stops playback and removes stale media when view permission is lost",async()=>{await act(async()=>host.querySelectorAll<HTMLButtonElement>("button")[0].click());expect(host.textContent).toContain("playing:one");state.permissionGranted=false;render();expect(host.querySelectorAll("audio")).toHaveLength(0);expect(host.textContent).toContain("closed:none");expect(pause).toHaveBeenCalled()});
  it("plays, pauses, switches, persists as one audio element, closes, and reopens",async()=>{const buttons=host.querySelectorAll<HTMLButtonElement>("button");await act(async()=>buttons[0].click());expect(host.textContent).toContain("playing:one");expect(host.querySelectorAll("audio")).toHaveLength(1);await act(async()=>buttons[2].click());expect(host.textContent).toContain("paused:one");await act(async()=>buttons[1].click());expect(host.textContent).toContain("playing:two");expect(host.querySelectorAll("audio")).toHaveLength(1);act(()=>buttons[3].click());expect(host.textContent).toContain("closed:none");await act(async()=>buttons[0].click());expect(host.textContent).toContain("playing:one");expect(play).toHaveBeenCalledTimes(3)});
  it("preserves the same playing audio element across AppLink member routes",async()=>{await act(async()=>host.querySelectorAll<HTMLButtonElement>("button")[0].click());const audio=host.querySelector('[data-testid="persistent-radio-audio"]');expect(audio).not.toBeNull();act(()=>host.querySelectorAll<HTMLAnchorElement>("a")[0].click());expect(host.textContent).toContain("/portal:playing:one");expect(host.querySelector('[data-testid="persistent-radio-audio"]')).toBe(audio);act(()=>host.querySelectorAll<HTMLAnchorElement>("a")[1].click());expect(host.textContent).toContain("/portal/services:playing:one");expect(host.querySelector('[data-testid="persistent-radio-audio"]')).toBe(audio);expect(host.querySelectorAll('[data-testid="persistent-radio-audio"]')).toHaveLength(1);expect(host.querySelector('[data-testid="persistent-radio-player"]')).not.toBeNull();expect(pause).not.toHaveBeenCalled()});
  it("preserves Radio ownership when navigating specifically to notifications",async()=>{await act(async()=>host.querySelectorAll<HTMLButtonElement>("button")[0].click());const audio=host.querySelector('[data-testid="persistent-radio-audio"]');act(()=>host.querySelectorAll<HTMLAnchorElement>("a")[2].click());expect(host.textContent).toContain("/portal/notifications:playing:one");expect(host.querySelector('[data-testid="persistent-radio-audio"]')).toBe(audio);expect(host.querySelectorAll('[data-testid="persistent-radio-audio"]')).toHaveLength(1)});
  it("closes Radio before livestream activation so the mini players cannot collide",async()=>{const buttons=host.querySelectorAll<HTMLButtonElement>("button");await act(async()=>buttons[0].click());act(()=>buttons[4].click());expect(host.textContent).toContain("closed:none");expect(host.querySelector('[data-testid="persistent-radio-player"]')).toBeNull();expect(pause).toHaveBeenCalled()});
  it("stops livestream before Radio begins",async()=>{await act(async()=>host.querySelectorAll<HTMLButtonElement>("button")[0].click());expect(stopLivestream).toHaveBeenCalledTimes(1)});
  it("clears on logout and tenant change",async()=>{const buttons=host.querySelectorAll<HTMLButtonElement>("button");await act(async()=>buttons[0].click());state.auth={churchId:"church-b",user:{id:"user-b"}};render();expect(host.textContent).toContain("closed:none");await act(async()=>host.querySelectorAll<HTMLButtonElement>("button")[0].click());state.auth={churchId:null,user:null};render();expect(host.textContent).toContain("closed:none")});
});
