import { describe, expect, it } from "vitest";
import { isPastIsoDate, MESSAGES, normalizeCommand, normalizeTanzanianPhone, paymentDecision, redactSecrets, serviceWindow, statusPatch, transition, verifyChallenge, verifyMetaSignature } from "../../supabase/functions/_shared/whatsapp-core";

const masses = [{ id: "m1", label: "07:00 Asubuhi", available: true }, { id: "m2", label: "10:00 Asubuhi", available: false }];
describe("WhatsApp Phase 1 core", () => {
  it("normalizes Tanzanian phones", () => { expect(normalizeTanzanianPhone("0712 345 678")).toBe("+255712345678"); expect(normalizeTanzanianPhone("+255712345678")).toBe("+255712345678"); expect(normalizeTanzanianPhone("123")).toBeNull(); });
  it("normalizes commands", () => expect(normalizeCommand("  anza   upya ")).toBe("ANZA UPYA"));
  it("starts every supported entry form", () => ["NIA YA MISA", "NIA", "MISA INTENTION", "NATAKA NIA", "NATAKA KUWEKA NIA", "MENU"].forEach((x) => expect(transition("IDLE", {}, x).state).toBe("SELECT_INTENTION_TYPE")));
  it("walks every Nia state transition", () => { let r = transition("IDLE", {}, "NIA"); r = transition(r.state, r.context, "1"); expect(r.state).toBe("ENTER_INTENTION_DETAILS"); r = transition(r.state, r.context, "Kwa ajili ya Maria"); expect(r.state).toBe("SELECT_DATE"); r = transition(r.state, r.context, "2030-01-01", { today: new Date("2029-01-01Z") }); expect(r.state).toBe("SELECT_MASS_TIME"); r = transition(r.state, r.context, "1", { availableMasses: masses }); expect(r.state).toBe("CONFIRM_SUMMARY"); r = transition(r.state, r.context, "ndiyo"); expect(r.state).toBe("AWAITING_PAYMENT"); });
  it("rejects invalid intention selections", () => expect(transition("SELECT_INTENTION_TYPE", {}, "99").state).toBe("SELECT_INTENTION_TYPE"));
  it("rejects past and invalid dates", () => { expect(isPastIsoDate("2025-01-01", new Date("2026-01-01Z"))).toBe(true); expect(isPastIsoDate("2026-99-01", new Date("2026-01-01Z"))).toBe(true); });
  it("rejects unavailable Mass slots", () => expect(transition("SELECT_MASS_TIME", {}, "2", { availableMasses: masses }).state).toBe("SELECT_MASS_TIME"));
  it("supports cancellation, restart, back and help", () => { expect(transition("SELECT_DATE", {}, "GHAIRI").state).toBe("CANCELLED"); expect(transition("CANCELLED", {}, "ANZA UPYA").state).toBe("SELECT_INTENTION_TYPE"); expect(transition("SELECT_DATE", {}, "RUDI").state).toBe("ENTER_INTENTION_DETAILS"); expect(transition("SELECT_DATE", {}, "MSAADA").message).toBe(MESSAGES.help); });
  it("calculates service window timestamps", () => expect(serviceWindow(new Date("2026-01-01T00:00:00Z"), 24).expiresAt).toBe("2026-01-02T00:00:00.000Z"));
  it("redacts nested secrets", () => expect(redactSecrets({ authorization: "Bearer abc", nested: { access_token: "abc" } })).toEqual({ authorization: "[REDACTED]", nested: { access_token: "[REDACTED]" } }));
  it("accepts a valid Meta HMAC and rejects invalid signatures", async () => { const body = '{"ok":true}', secret = "test-secret"; const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const bytes = new Uint8Array(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(body))); const signature = `sha256=${[...bytes].map((b) => b.toString(16).padStart(2, "0")).join("")}`; expect(await verifyMetaSignature(body, signature, secret)).toBe(true); expect(await verifyMetaSignature(body, "sha256=00", secret)).toBe(false); });
  it("validates webhook verification token and challenge", () => { expect(verifyChallenge(new URLSearchParams("hub.mode=subscribe&hub.verify_token=ok&hub.challenge=42"), "ok")).toEqual({ valid: true, challenge: "42" }); expect(verifyChallenge(new URLSearchParams("hub.mode=subscribe&hub.verify_token=no"), "ok").valid).toBe(false); });
  it("maps delivery, read, and failure callbacks", () => { expect(statusPatch("delivered", 1)).toHaveProperty("delivered_at"); expect(statusPatch("read", 1)).toHaveProperty("read_at"); expect(statusPatch("failed", 1, "bad")).toMatchObject({ status: "failed", failure_reason: "bad" }); });
  it("keeps payment callbacks idempotent and routes review exceptions", () => { expect(paymentDecision({ alreadyProcessed: true, verified: true, slotAvailable: true, autoConfirm: true, manualReview: false }).outcome).toBe("duplicate"); expect(paymentDecision({ alreadyProcessed: false, verified: false, slotAvailable: true, autoConfirm: true, manualReview: false }).outcome).toBe("unverified"); expect(paymentDecision({ alreadyProcessed: false, verified: true, slotAvailable: false, autoConfirm: true, manualReview: false }).outcome).toBe("capacity_conflict"); expect(paymentDecision({ alreadyProcessed: false, verified: true, slotAvailable: true, autoConfirm: false, manualReview: true }).outcome).toBe("manual_review"); expect(paymentDecision({ alreadyProcessed: false, verified: true, slotAvailable: true, autoConfirm: true, manualReview: false }).confirm).toBe(true); });
});
