import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Pause, Play, Plus, Radio, Trash2, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { deletePlatformRadioStation, fetchPlatformRadioStations, savePlatformRadioStation, type PlatformRadioDirectoryStation } from "@/lib/church-radio";

const empty = { id: "", name: "", streamUrl: "", websiteUrl: "", logoUrl: "", description: "", provider: "", streamFormat: "", metadataUrl: "", isActive: true, isApproved: false };
type FormState = typeof empty;
type TestState = "idle" | "loading" | "working" | "failed";

export default function RadioDirectoryPage() {
  const queryClient = useQueryClient(); const { toast } = useToast();
  const [open, setOpen] = useState(false); const [form, setForm] = useState<FormState>(empty);
  const [testingId, setTestingId] = useState<string | null>(null); const [testState, setTestState] = useState<TestState>("idle");
  const audioRef = useRef<HTMLAudioElement | null>(null);
  useEffect(() => () => { audioRef.current?.pause(); }, []);
  const stations = useQuery({ queryKey: ["platform-radio-directory"], queryFn: fetchPlatformRadioStations });
  const refresh = () => void queryClient.invalidateQueries({ queryKey: ["platform-radio-directory"] });
  const save = useMutation({ mutationFn: () => savePlatformRadioStation({ ...form, id: form.id || undefined, websiteUrl: form.websiteUrl || null, logoUrl: form.logoUrl || null, description: form.description || null, provider: form.provider || null, streamFormat: form.streamFormat || null, metadataUrl: form.metadataUrl || null }), onSuccess: () => { refresh(); setOpen(false); toast({ title: "Radio station saved" }); }, onError: (error) => toast({ title: "Unable to save station", description: error instanceof Error ? error.message : "Try again.", variant: "destructive" }) });
  const remove = useMutation({ mutationFn: deletePlatformRadioStation, onSuccess: refresh, onError: (error) => toast({ title: "Unable to delete station", description: error instanceof Error ? error.message : "The station may still be selected by a church.", variant: "destructive" }) });
  const edit = (station: PlatformRadioDirectoryStation) => { setForm({ id: station.id, name: station.name, streamUrl: station.streamUrl, websiteUrl: station.websiteUrl ?? "", logoUrl: station.logoUrl ?? "", description: station.description ?? "", provider: station.provider ?? "", streamFormat: station.streamFormat ?? "", metadataUrl: station.metadataUrl ?? "", isActive: station.isActive, isApproved: station.isApproved }); setOpen(true); };
  const test = async (station: PlatformRadioDirectoryStation) => { audioRef.current?.pause(); if (testingId === station.id && testState === "working") { setTestingId(null); setTestState("idle"); return; } const audio = new Audio(station.streamUrl); audio.preload = "none"; audioRef.current = audio; setTestingId(station.id); setTestState("loading"); audio.addEventListener("playing", () => setTestState("working"), { once: true }); audio.addEventListener("error", () => setTestState("failed"), { once: true }); try { await audio.play(); } catch { setTestState("failed"); } };
  return <main className="mx-auto max-w-5xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold tracking-[0.18em] text-red-500">PLATFORM CATALOGUE</p><h1 className="mt-2 text-3xl font-bold">Radio Directory</h1><p className="mt-2 text-sm text-muted-foreground">Approve and maintain technical stream configuration for every church.</p></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button onClick={() => setForm(empty)}><Plus className="mr-2 h-4 w-4" />Add Radio Station</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{form.id ? "Edit Radio Station" : "Add Radio Station"}</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Label>Name<Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Label><Label>Provider<Input value={form.provider} onChange={(e) => setForm({ ...form, provider: e.target.value })} /></Label><Label className="sm:col-span-2">Stream URL<Input type="url" value={form.streamUrl} onChange={(e) => setForm({ ...form, streamUrl: e.target.value })} placeholder="https://…" /></Label><Label>Website URL<Input type="url" value={form.websiteUrl} onChange={(e) => setForm({ ...form, websiteUrl: e.target.value })} /></Label><Label>Logo URL<Input type="url" value={form.logoUrl} onChange={(e) => setForm({ ...form, logoUrl: e.target.value })} /></Label><Label>Stream format<Input value={form.streamFormat} onChange={(e) => setForm({ ...form, streamFormat: e.target.value })} placeholder="MP3, AAC, HLS…" /></Label><Label>Description<Input value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Label><Label className="sm:col-span-2">Metadata URL (optional)<Input type="url" value={form.metadataUrl} onChange={(e) => setForm({ ...form, metadataUrl: e.target.value })} placeholder="https://…" /></Label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })} />Stream active</label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={form.isApproved} onChange={(e) => setForm({ ...form, isApproved: e.target.checked })} />Approved</label><Button className="sm:col-span-2" disabled={!form.name.trim() || !form.streamUrl.trim() || save.isPending} onClick={() => save.mutate()}>Save Station</Button></div></DialogContent></Dialog></header>
    <div className="space-y-3">{stations.data?.map((station) => { const state = testingId === station.id ? testState : "idle"; return <Card key={station.id}><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><span className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-red-500/10">{station.logoUrl ? <img src={station.logoUrl} alt="" className="h-full w-full object-cover" /> : <Radio className="h-6 w-6 text-red-500" />}</span><div className="min-w-0 flex-1"><h2 className="font-bold">{station.name}</h2><p className="text-sm text-muted-foreground">Provider: {station.provider || "Not specified"}</p><div className="mt-2 flex flex-wrap gap-2 text-xs font-bold"><span className={station.isApproved ? "text-emerald-600" : "text-amber-600"}>{station.isApproved ? "✓ Approved" : "⚠ Awaiting approval"}</span><span className={station.isActive ? "text-emerald-600" : "text-muted-foreground"}>{station.isActive ? "✓ Stream active" : "Inactive"}</span>{state !== "idle" ? <span>{state === "loading" ? "Loading…" : state === "working" ? "Working" : "Failed"}</span> : null}</div><details className="mt-2 text-xs text-muted-foreground"><summary className="cursor-pointer">Technical details</summary><p className="mt-1 break-all">{station.streamUrl}</p></details></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void test(station)}>{state === "working" ? <Pause className="mr-2 h-4 w-4" /> : state === "failed" ? <XCircle className="mr-2 h-4 w-4" /> : state === "loading" ? <CheckCircle2 className="mr-2 h-4 w-4 animate-pulse" /> : <Play className="mr-2 h-4 w-4" />}Test Stream</Button><Button variant="outline" onClick={() => edit(station)}>Edit</Button><Button variant="ghost" size="icon" aria-label={`Delete ${station.name}`} onClick={() => remove.mutate(station.id)}><Trash2 className="h-4 w-4" /></Button></div></CardContent></Card>; })}</div>
  </main>;
}
